# Generated by Django 3.2.3 on 2022-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_auto_20220326_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrer',
            name='article',
        ),
        migrations.RemoveField(
            model_name='entrer',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='entrer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='User',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='sorties',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='article',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='article',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='article',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='numero',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='article',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_entree',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantité_en_vrac',
        ),
        migrations.RemoveField(
            model_name='article',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='stock.Article'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Entrer',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='Sortir',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
